language: cpp

group: travis_latest

git:
  submodules: false

matrix:
  include:
    - { os: linux, dist: xenial, compiler: gcc, env: BUILD_TYPE=Coverage ENABLE_DOCS=yes }
    - { os: linux, dist: xenial, compiler: gcc, env: BUILD_TYPE=Debug }
    - { os: linux, dist: xenial, compiler: gcc, env: BUILD_TYPE=Release }
    - { os: linux, dist: xenial, compiler: clang, env: BUILD_TYPE=Debug }
    - { os: linux, dist: xenial, compiler: clang, env: BUILD_TYPE=Release }
    - { os: osx, osx_image: xcode10.1, compiler: gcc, env: BUILD_TYPE=Debug }
    - { os: osx, osx_image: xcode10.1, compiler: gcc, env: BUILD_TYPE=Release }
    - { os: osx, osx_image: xcode10.1, compiler: clang, env: BUILD_TYPE=Debug }
    - { os: osx, osx_image: xcode10.1, compiler: clang, env: BUILD_TYPE=Release }
    - { os: windows, env: BUILD_TYPE=Debug }
    - { os: windows, env: BUILD_TYPE=Release }

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
      - g++-8
      - ninja-build
      - doxygen
  homebrew:
    packages:
      - gcc
      - ninja

install: |
  source scripts/travis_install.sh

script: |
  source scripts/travis_script.sh

after_success: |
  source scripts/travis_success.sh

#deploy:
#  - provider: pages
#    local-dir: docs
#    skip-cleanup: true
#    github-token: $GITHUB_TOKEN
#    on:
#      branch: master
#      condition: $ENABLE_DOCS = yes
