name: Build

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ubuntu, macos]
        compiler: [gcc, clang]
        include:
          - os: windows
            compiler: msvc

    steps:
      - uses: actions/checkout@v2

      - name: Configure buildsystem
        run: |
          case "${{ matrix.compiler }}" in
            gcc)
              CC=gcc-9 CXX=g++-9
              ;;
            clang)
              CC=clang CXX=clang++
              ;;
          esac
          case "${{ matrix.os }}" in
            ubuntu|macos)
              brew install ninja
              cmake . -G "Ninja Multi-Config" -DCMAKE_CONFIGURATION_TYPES="Debug;Release"
              ;;
            windows)
              cmake . -G "Visual Studio 16 2019" -A x64
              ;;
          esac

      - name: Debug build/test
        run: |
          cmake --build . --config Debug
          ctest --build-config Debug --output-on-failure

      - name: Release build/test
        run: |
          cmake --build . --config Release
          ctest --build-config Release --output-on-failure
